server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/noerms
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.cache.type=none
app.jwt.secret=noerms-secret-key-university-buea-cef476-2024-production-minimum-64-chars
app.jwt.expiration=86400000
logging.level.root=WARN
logging.level.com.noerms=INFO
